name: Checkov

on:
  push:
    branches: [ main ]

jobs:
  discover:
    runs-on: ubuntu-latest

    outputs:
      folders: ${{ steps.folders.outputs.folders }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Determine changed folders
        id: folders
        run: |
          dirs=""

          while IFS= read -r file; do
            if [[ "$file" == apps/*/* ]]; then
              folder="${file#apps/}"     # remove apps/
              folder="${folder%%/*}"     # take folder name
              dirs="$dirs apps/$folder"
            fi

            if [[ "$file" == platform/* ]]; then
              dirs="$dirs platform"
            fi
          done <<< "$CHANGED"

          dirs=$(echo "$dirs" | tr ' ' '\n' | sed '/^\s*$/d' | sort -u)

          echo "Resolved folders:"
          echo "$dirs"

          if [[ -z "$dirs" ]]; then
            json='[]'
          else
            json=$(echo "$dirs" | jq -R . | jq -s -c .)
          fi

          echo "folders=$json" >> "$GITHUB_OUTPUT"
          echo "Final JSON: $json"

  checkov:
    needs: discover
    runs-on: ubuntu-latest
    if: ${{ needs.discover.outputs.folders != '[]' }}

    strategy:
      fail-fast: false
      matrix:
        folder: ${{ fromJson(needs.discover.outputs.folders) }}

    steps:
      - uses: actions/checkout@v4
      - run: pip install checkov

      - name: Run Checkov on folder
        run: |
          echo "Scanning: ${{ matrix.folder }}"
          checkov -d "${{ matrix.folder }}"
