name: Checkov

on:
  pull_request:
  push:

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      folders: ${{ steps.set-matrix.outputs.folders }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - name: Get changed files
        id: changed-files
        run: |
            if ${{ github.event_name == 'pull_request' }}; then
                echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
            else
                echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
            fi
      - name: List changed folders
        run: |
          dirs=""
          for file in ${{ steps.changed-files.outputs.changed_files }}; do
            dir=$(dirname "$file")

            # Keep only apps/<folder> and platform
            if [[ "$dir" == apps/* ]]; then
              top="apps/${dir#apps/}"   # remove apps/
              top="${top%%/*}"          # extract first folder
              dirs="$dirs apps/$top"
            fi

            if [[ "$dir" == platform ]]; then
              dirs="$dirs platform"
            fi
          done
          echo $dirs
          # Deduplicate and turn into JSON array
          if [[ -z "$dirs" ]]; then
            json="[]"
          else
            json=$(echo $dirs | tr ' ' '\n' | sort -u | jq -R . | jq -s -c .)
          fi

          echo "folders=$json" >> "$GITHUB_OUTPUT"
          echo "Final JSON: $json"



  # checkov:
  #   needs: discover
  #   runs-on: ubuntu-latest
  #   if: ${{ needs.discover.outputs.folders != '[]' }}

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       folder: ${{ fromJson(needs.discover.outputs.folders) }}

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Install Checkov
  #       run: pip install checkov

  #     - name: Run Checkov on ${{ matrix.folder }}
  #       run: |
  #         echo "Running Checkov on: ${{ matrix.folder }}"
  #         checkov -d "${{ matrix.folder }}"
