name: Terraform CI
permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
  push:

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      folders: ${{ steps.folders.outputs.folders }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - name: Get changed files
        id: changed-files
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
            echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
          else
            echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
          fi

      - name: List changed folders
        id: folders
        run: |
          dirs=""

          for file in ${{ steps.changed-files.outputs.changed_files }}; do
            path="$file"

            if [[ "$path" == apps/*/* ]]; then
              app_dir=$(echo "$path" | cut -d'/' -f1-2)
              dirs="$dirs $app_dir"
            fi

            if [[ "$path" == platform/* ]]; then
              dirs="$dirs platform"
            fi
          done

          dirs=$(echo "$dirs" | tr ' ' '\n' | sed '/^\s*$/d' | sort -u)

          if [[ -z "$dirs" ]]; then
            json="[]"
          else
            json=$(echo $dirs | tr ' ' '\n' | sort -u | jq -R . | jq -s -c .)
          fi

          echo "folders=$json" >> "$GITHUB_OUTPUT"

  checkov:
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.folders != '[]' }}

    strategy:
      fail-fast: false
      matrix:
        folder: ${{ fromJson(needs.changes.outputs.folders) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov on ${{ matrix.folder }}
        run: |
          checkov -d "${{ matrix.folder }}"

  docs:
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.folders != '[]' }}

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        folder: ${{ fromJson(needs.changes.outputs.folders) }}

    steps:
      - name: Checkout repo (write enabled)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest changes
        run: |
          git fetch origin main
          git pull origin main --rebase

      - name: Fix Git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Generate Terraform Docs
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: ${{ matrix.folder }}/
          output-file: README.md
          output-method: inject
          git-push: true
